appTeatro/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('index');

Route::resource('users', 'UsersController');
Route::resource('reservation', 'ReservationController');
Route::resource('seat', 'SeatController');

appTeatro/resources/views/dashboard.blade.php
@extends('layouts.app')

@section('title', 'Panel | TEATRO')

@section('main-navbar')
<header class="header">
    <nav class="navbar">

        <div class="container-fluid">
            <div class="navbar-holder d-flex align-items-center justify-content-between">
          
                <!-- Navbar Header-->
                <div class="navbar-header">
                
                    <!-- Navbar Brand -->
                    <a href="{{ route('index') }}" class="navbar-brand d-none d-sm-inline-block">
                        <div class="brand-text d-none d-lg-inline-block"><span>Panel </span><strong>Teatro</strong></div>
                        <div class="brand-text d-none d-sm-inline-block d-lg-none"><strong>P|Teatro</strong></div>
                    </a>
                
                    <!-- Toggle Button-->
                    <a id="toggle-btn" href="#" class="menu-btn active"><span></span><span></span><span></span></a>
                </div>

            </div>
        </div>
    </nav>
</header>
@endsection

@section('side-navbar')
<nav class="side-navbar">

    <!-- Sidebar Header-->
    <div class="sidebar-header d-flex align-items-center">
        <div class="avatar">
            <img src="{{ asset('img/avatar_user.jpg') }}" alt="..." class="img-fluid rounded-circle">
        </div>
        <div class="title">
            <h1 class="h4">Sonia Silva</h1>
            <p>Bienvenida</p>
        </div>
    </div>

    <!-- Sidebar Navidation Menus-->
    <ul class="list-unstyled">
        <li class="active"><a href="{{ route('index') }}"> <i class="icon-home"></i>Inicio </a></li>
        <li><a href="{{ route('users.index') }}"> <i class="fa fa-users" aria-hidden="true"></i>Clientes </a></li>
        <li><a href="{{ route('reservation.index') }}"> <i class="fa fa-ticket" aria-hidden="true"></i>Reservas </a></li>
    </ul>
</nav>
@endsection

@section('content-inner')
<div class="content-inner">
    
    <!-- Page Header-->
    <header class="page-header">
        <div class="container-fluid">
            <h2 class="no-margin-bottom">Panel Administrador</h2>
        </div>
    </header>

    <!-- Dashboard Counts Section-->
    <section class="dashboard-counts no-padding-bottom">
        <div class="container-fluid">
            <div class="row bg-white has-shadow">

                <!-- Item -->
                <div class="col-xl-6 col-sm-6">
                    <div class="item d-flex align-items-center">
                        <div class="icon bg-green"><i class="fa fa-users" aria-hidden="true"></i></div>
                        <div class="title">
                            <span>Clientes<br>Registrados</span>
                            <div class="progress">
                                <div role="progressbar" style="width: 20%; height: 4px;" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" class="progress-bar bg-green"></div>
                            </div>
                        </div>
                        <div class="number"><strong>{{ $countUsers }}</strong></div>
                    </div>
                </div>
                
                <!-- Item -->
                <div class="col-xl-6 col-sm-6">
                    <div class="item d-flex align-items-center">
                        <div class="icon bg-orange"><i class="fa fa-ticket" aria-hidden="true"></i></div>
                        <div class="title">
                            <span>Reservas<br>Registradas</span>
                            <div class="progress">
                                <div role="progressbar" style="width: 50%; height: 4px;" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" class="progress-bar bg-orange"></div>
                            </div>
                        </div>
                        <div class="number"><strong>{{ $countReservations }}</strong></div>
                    </div>
                </div>
          
            </div>
        </div>
    </section>

    <!-- Projects Section-->
    <section class="projects">
        <div class="container-fluid">

            @foreach($listTheaterplay as $theaterplay)
            <!-- Project-->
            <div class="project">
                <div class="row bg-white has-shadow">
                    <div class="left-col col-lg-6 d-flex align-items-center justify-content-between">
                        <div class="project-title d-flex align-items-center">
                            <div class="image has-shadow"><img src="http://t1.gstatic.com/images?q=tbn:ANd9GcRwQUPHlv9XT7-8IBSCjKWZx7RvZZdu-_qFn0LvPoMXUFmNmdqy" alt="..." class="img-fluid"></div>
                            <div class="text">
                                <h3 class="h4">{{ $theaterplay['name'] }}</h3><small>{{ $theaterplay['author'] }}</small>
                            </div>
                        </div>
                        <div class="project-date"><span class="hidden-sm-down">{{ $theaterplay['date'] }}</span></div>
                    </div>
                    <div class="right-col col-lg-6 d-flex align-items-center">
                        <!-- <div class="time"><i class="fa fa-clock-o"></i>{{ $theaterplay['date'] }}</div> -->
                        <div class="comments"><i class="fa fa-exchange" aria-hidden="true"></i>Asientos: 50</div>
                        <div class="project-progress">
                            <div class="progress">
                                <div role="progressbar" style="width: 70%; height: 6px;" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" class="progress-bar bg-red"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            @endforeach

        </div>
    </section>
      
    <!-- Page Footer-->
    <footer class="main-footer">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-6">
                    <p>NRS GROUP &copy; 2018</p>
                </div>
                <div class="col-sm-6 text-right">
                    <p>Desarrollado por <a href="https://www.linkedin.com/in/francisco-gerardino/" class="external">Francisco Gerardino</a></p>
                </div>
            </div>
        </div>
    </footer>

</div>
@endsection

appTeatro/resources/views/login.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="Test de prueba tecnica NRS">
        <meta name="author" content="Francisco Gerardino">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <title>Teatro</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet" type="text/css">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

        <!-- FontAwesome -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
        
        <style>
            html, body {
                height: 100%;
            }

            body {
                display: -ms-flexbox;
                display: flex;
                -ms-flex-align: center;
                align-items: center;
                padding-top: 40px;
                padding-bottom: 40px;
                background-color: #f5f5f5;
            }

            .form-signin {
                width: 100%;
                max-width: 330px;
                padding: 15px;
                margin: auto;
            }
            .form-signin .checkbox {
                font-weight: 400;
            }
            .form-signin .form-control {
                position: relative;
                box-sizing: border-box;
                height: auto;
                padding: 10px;
                font-size: 16px;
            }
            .form-signin .form-control:focus {
                z-index: 2;
            }
            .form-signin input[type="email"] {
                margin-bottom: -1px;
                border-bottom-right-radius: 0;
                border-bottom-left-radius: 0;
            }
            .form-signin input[type="password"] {
                margin-bottom: 10px;
                border-top-left-radius: 0;
                border-top-right-radius: 0;
            }
        </style>
    </head>
    <body>
        <form class="form-signin" method="post" action="{{ route('login') }}">
            {{ csrf_field() }}
            <h1 class="text-center h3 mb-3 font-weight-normal">Inicio de Sesión</h1>

            <label for="inputLogin" class="sr-only">Login</label>
            <input type="email" id="inputLogin" class="form-control" placeholder="Login" required autofocus>

            <label for="inputPassword" class="sr-only">Password</label>
            <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>

            <button class="btn btn-md btn-primary btn-block" type="submit">Ingresar</button>
            <button class="btn btn-md btn-success btn-block" type="button" data-toggle="modal" data-target="#registerModal">Registro</button>

            <div id="message-register"></div>
        </form>

        <div class="modal fade" id="registerModal" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <form method="post" action="{{ route('users.store') }}">
                        {{ csrf_field() }}
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Registro de Usuario</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="container-fluid">
                                <div class="row">
                                    <div class="col-md-6 mb-3">
                                        <div class="form-group">
                                            <label for="first-name" class="col-form-label">Nombre</label>
                                            <div class="input-group">
                                                <div class="input-group-prepend">
                                                    <span class="input-group-text"><i class="fas fa-edit"></i></span>
                                                </div>
                                                <input type="text" class="form-control" id="first-name" name="firstname" placeholder="Ingrese su nombre" required>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6 mb-3">
                                        <div class="form-group">
                                            <label for="last-name" class="col-form-label">Apellido</label>
                                            <div class="input-group">
                                                <div class="input-group-prepend">
                                                    <span class="input-group-text"><i class="fas fa-edit"></i></span>
                                                </div>
                                                <input type="text" class="form-control" id="last-name" name="lastname" placeholder="Ingrese su apellido" required>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-4 mb-3">
                                        <div class="form-group">
                                            <label for="sex" class="col-form-label">Sexo</label>
                                            <div class="input-group">
                                                <div class="custom-control custom-radio custom-control-inline">
                                                    <input type="radio" id="woman" name="sex" value="F" class="custom-control-input">
                                                    <label class="custom-control-label" for="woman"><i class="fas fa-female"></i></label>
                                                </div>
                                                <div class="custom-control custom-radio custom-control-inline">
                                                    <input type="radio" id="man" name="sex" value="M" class="custom-control-input">
                                                    <label class="custom-control-label" for="man"><i class="fas fa-male"></i></label>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-8 mb-3">
                                        <div class="form-group">
                                            <label for="phone" class="col-form-label">Telefono</label>
                                            <div class="input-group">
                                                <div class="input-group-prepend">
                                                    <span class="input-group-text"><i class="fas fa-phone"></i></span>
                                                </div>
                                                <input type="text" class="form-control" id="phone" name="phone" placeholder="Ingrese su telefono" required>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="email" class="col-form-label">Email</label>
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text"><i class="fas fa-at"></i></span>
                                        </div>
                                        <input type="email" class="form-control" id="email" name="email" placeholder="usuario@email.com" required>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="password" class="col-form-label">Password</label>
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text"><i class="fas fa-unlock-alt"></i></span>
                                        </div>
                                        <input type="password" class="form-control" id="password" name="password" placeholder="xxxxxx" required>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="re-password" class="col-form-label">Confirmación de Password</label>
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text"><i class="fas fa-unlock-alt"></i></span>
                                        </div>
                                        <input type="password" class="form-control" id="re-password" placeholder="xxxxxx" required>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                            <button type="submit" class="btn btn-primary" id="btn-register">Guardar</button>
                            
                            <input type="hidden" id='status-register' name="status" value="{{ $errorRegister }}" data-email="{{ $emailPrevious }}" />
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

        <script src="{{ asset('js/complement-register.js') }}" type="text/javascript"></script>
    </body>
</html>